### PR TITLE
Integrate Phytos31

### LINKED ISSUE #35: Fix test PyPI action
The publishing of test PyPI fails because one already exists on the repository under the same version. I think having it use manual invocation via `workflow_dispatch` is the better option. Then the dev can still manually check that changes work. For PRs the manual check should be specifically mentioned.

### LINKED ISSUE #58: Integrate PHYTOS 31 leaf wetness sensor
**Describe the Enhancement**
Read a voltage measurement from the leaf wetness sensor and upload over LoRa to Dirtviz.

**Benefits**
Add a new sensor to the platform

**Possible Drawbacks**
N/A

**Additional Context**
The scope of the work is the following:
- Measure voltage from the sensor
- Add protobuf message for leaf wetness sensor
- Integrate with sensor library to TX measurements

Will need to coordinate with Dirtviz team to add capabilities to display data.

Also @jmadden173 will update the issue with fields required for the leaf wetness sensor. Currently will just be voltage, but maybe some calibration or offset to convert 24 bit ADC reading to 16 bit to save space. It looks like we only need a 12 bit measurement according to the datasheet.

Link to sensor page: https://metergroup.com/products/phytos-31/
Manual: https://library.metergroup.com/Manuals/20434_PHYTOS31_Manual_Web.pdf
^ the sensor page is broken for me so here's the manual if that's the case

Issues #53 #50 are blockers.

### LINKED ISSUE #73: Protobuf python library decode TypeError
**Describe the Bug**

**To Reproduce**

1. Install `soil-power-sensor-protobuf` package
2. Run `decode_measurement` on valid data

```
...
backend-1  |   File "/app/backend/api/resources/util.py", line 32, in process_measurement
backend-1  |     meas = decode_measurement(data)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.11/site-packages/soil_power_sensor_protobuf/decode.py", line 53, in decode_measurement
backend-1  |     meta_dict = MessageToDict(meas.meta, including_default_value_fields=True)
backend-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  | TypeError: MessageToDict() got an unexpected keyword argument 'including_default_value_fields'
```

**Expected Behavior**
No error is thrown

**Screenshots**
N/A

**Environment**

Linux

**Additional Context**

The `soil-power-sensor-protobuf` python package specifies `protobuf` requirement but no version. Therefore when protobuf was update `MessageToDict` has changed causing excpetions on new installations. Didn't realize it since I was decoding messages on original venv.

### PR DESCRIPTION
**Pull request by jmadden173**
**Name/Affiliation/Title**
John, UCSC, protector of code (aka maintainer)

**Purpose of the PR**
Add support for the Phytos31 leaf wetness sensor

**Development Environment**
`Linux spruce 6.8.2-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000 x86_64 GNU/Linux`
PlatformIO Core, version 6.1.7
Used ST-Link V3 MINIE

**Test Procedure**
Connect the Phytos31 sensor to the `V+` terminal and ground `V-` to put in single ended configuration. First run the example code to see raw voltage outputs printed over UART. Place hand on Phytos31, the output should change.

In the same configuration run the default env and check for changes on [Dirtviz](https://dirtviz.jlab.ucsc.edu/dashboard) under cell name `demo`.

**Additional Context**
Python protobuf package dependency versions has been updated to hopefully fix #73. Also, the `publish-to-testpypi` is reconfigured to only run on workflow dispatch (#35).

Closes #35
Closes #58 
Closes #73

### CODE REVIEW

File: stm32/Src/phytos31.c [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+}
+
+size_t Phytos31_measure(uint8_t *data) {
+  // get timestamp
+  time_t ts = TimestampNow();
+  phytos_measurments measurment;
+
+  // read voltage
+  measurment = Phytos31GetMeasurment();
+  double adc_voltage_float = ((double) measurment.phytos31_raw) / 1000.;
```
Comment (jmadden173) [inline stm32/Src/phytos31.c:37]: What is the `/ 1000.` for? To me it seems like a calibration of sort but `Phytos31GetMeasurement` only returns raw?

File: stm32/Src/phytos31.c [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+  return ADC_init();
+}
+
+phytos_measurments Phytos31GetMeasurment(){
+  phytos_measurments measurments;
+  measurments.phytos31_raw = (double) ADC_readVoltage();
+  return measurments;
+}
+
+size_t Phytos31_measure(uint8_t *data) {
```
Comment (jmadden173) [inline stm32/Src/phytos31.c:30]: Naming convention

File: stm32/Src/syscalls.c
Comment (jmadden173) [inline stm32/Src/syscalls.c:1]: Afaik this is an artifact from CubeMX. All the calls are weak so we should be able to delete it.

File: stm32/Src/sysmem.c
Comment (jmadden173) [inline stm32/Src/sysmem.c:1]: Same as `syscalls.c`. Delete

**Review by jmadden173 — COMMENTED** [review]
Some extraneous files should be deleted. Added a few questions for @stevegtaylor for the Phytos31 code.

Need to add a unit test for the Phytos31

File: stm32/Src/phytos31.c [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+#include <string.h>
+
+#include "phytos31.h"
+#include "transcoder.h"
+
+HAL_StatusTypeDef Phytos31Init(){
+  return ADC_init();
+}
+
+phytos_measurments Phytos31GetMeasurment(){
```
[the remark this answers is not in the document]
Comment (stevegtaylor) [reply stm32/Src/phytos31.c:24]: not currently, can be integrated

File: stm32/Src/phytos31.c (hunk 1 above)
Comment (stevegtaylor) [reply stm32/Src/phytos31.c:37]: this is an error, i copied adc_measure exactly and forgot to remove the scalar.

File: stm32/Src/phytos31.c (hunk 2 above)
Comment (stevegtaylor) [reply stm32/Src/phytos31.c:30]: `size_t ADC_measure(uint8_t *data) {`

comes from this naming convention defined in `ads.c`

File: stm32/Src/syscalls.c
Comment (stevegtaylor) [reply stm32/Src/syscalls.c:1]: Like delete the whole file?

Comment (jmadden173) [reply stm32/Src/syscalls.c:1]: Yeah I don't see why we need it. Less files = less confusing for people looking at the code. But check that everything doesn't explode if you do.

File: stm32/Src/phytos31.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (jmadden173) [reply stm32/Src/phytos31.c:24]: I think that would be good to add so that data with errors won't be added to the buffer. That is a bug that I don't want to have to track down. In `Phytos31_measure` you can return `-1` as an error indicator and it won't be added to the buffer.

**Review by stevegtaylor — APPROVED** [review]

**Comment by stevegtaylor** [comment]
I didn't delete `syscalls.c` or `sysmem.c` because I don't have my testing set up with me. So I can't verify it doesn't break everything.
